name: Build

on: [create]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_WINDOWS: AMD64 x86 ARM64
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      
      - name: Push wheel
        run: |
          git config --global user.name "YuanyueLi"
          git config --global user.email "liyuanyue@gmail.com"
          git checkout -b wheels
          git add .
          git commit -m "Add wheels"
          git push origin wheels