name: Build and Publish

on: [workflow_dispatch]

jobs:
  # build_wheels:
  #   name: Build wheels on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [windows-2019]

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Build wheels
  #       uses: pypa/cibuildwheel@v2.13.1
  #       env:
  #         CIBW_ARCHS_MACOS: x86_64 arm64
  #         CIBW_ARCHS_LINUX: auto
  #         CIBW_ARCHS_WINDOWS: AMD64 x86
  #         CIBW_SKIP: pp*

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: dist/*.tar.gz

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload to PyPI
    # needs: [build_wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}